# Generated by Django 3.1.1 on 2020-10-01 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
